[default_session]
# startup_command = "nvim +GoToFile"

[[session]]
name = "Yang"
path = "~/code/github"

[[session]]
name = "Obsidian"
path = "~/code/github/LeeOnOnObsidian/content"

[[session]]
name = "Web Site"
path = "~/code/github/web-site"

[[session]]
name = "5EPlay"
path = "~/code/5eplay"

[[session]]
name = "GGPlay"
path = "~/code/5eplay/gg-play/"

[[session]]
name = "Github"
path = "~/code/github/"

[[session]]
name = "Home ğŸ›–"
path = "~"

[[session]]
name = "Code ğŸ’»"
path = "~/code"

[[session]]
name = "Dotfiles ğŸ“"
path = "~/.local/share/chezmoi/"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
