[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "Code ğŸ’»"
path = "~/code"
startup_command = "l"

[[session]]
name = "Dotfiles ğŸ“"
path = "~/.local/share/chezmoi/"
startup_command = "nvim"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "spf"
