[default_session]
startup_command = "nvim +GoToFile"

[[session]]
name = "Yang ğŸ”¥"
path = "~/code/github"
startup_command = "ls"

[[session]]
name = "5EPlay ğŸ–¥ï¸"
path = "~/code/5eplay"
startup_command = "ls"

[[session]]
name = "Home ğŸ›–"
path = "~"
startup_command = "ls"

[[session]]
name = "Code ğŸ’»"
path = "~/code"
startup_command = "ls"

[[session]]
name = "Dotfiles ğŸ“"
path = "~/.local/share/chezmoi/"
startup_command = "nvim"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "spf"
